### ISSUE TITLE
How to run / reproduce issue

### ISSUE THREAD

**Issue by chrisblossom** [alienriver49/clean-webpack-plugin-issue-146#1]
Thanks for the repo!

Please advise how to run this repository to reproduce the issue. The only npm script is build and only runs webpack once.

There is also a nested `package.json` and `tsconfig-build.json` I find confusing.

**Comment by alienriver49** [comment]
I know you resolved clean-webpack-plugin issue 146, at least the portion I duplicated with this repository, but I have added steps on how to reproduce if you do need them.

The first tsconfig is for development and the second tsconfig-build is for the webpack build. It's something we do internally since we usually have different tsconfig files within a repository (i.e. tsconfig-build, tsconfig-test).
